### ISSUE TITLE
Prebuilt wheels for arm64

### ISSUE THREAD

**Issue by exciteabletom** [sass/libsass-python#341]
Hello, 

It would be awesome to have prebuilt binaries for arm64, compiling the wheel on old Raspberry Pis is a hassle.

I have no experience with Azure pipelines so I won't make a PR, but I think the solution is simply changing `architectures: [x64, x86]` to `architectures: [x64, x86, arm64]` in `azure-pipelines.yml`.

Cheers

**Comment by asottile** [comment]
unfortunately before there is a specified standard for arm wheels in manylinux I won't be providing potentially non-complaint wheels (I understand that pypi allows you to upload them, but there isn't proper auditwheel tooling for arm yet)

you may be able to use piwheels though which builds specifically for your usecase: https://www.piwheels.org/simple/libsass/

**Comment by asottile** [comment]
also azure pipelines does not support anything but x86_64 at the moment

**Comment by exciteabletom** [comment]
Thanks for the help Anthony!

**Comment by kraptor** [comment]
I think people keep opening new bugs related to this one (as I did) because this one is closed and doesn't appear when searching for open bugs (why closing if not solved/implemented?).

In any case, the two mentioned issues, @asottile, seem to be sorted out as of today:
* As mentioned in #470, there is manylinux support for aarch64 as `manylinux2014_aarch64` (see PEP599 and PEP600): https://github.com/pypa/manylinux
* There is support in Azure to target Linux ARM64 since 2020: https://azure.microsoft.com/en-us/updates/azure-devops-pipelines-introduces-support-for-linuxarm64/

What I'm not aware is... does Azure not provide ARM64 runners for opensource projects? Is it paid? How can we help to add the pipeline for ARM64 on your behalf?

Thanks!

**Comment by billcrook** [comment]
FTR, another workaround is to install sass as a system package and set a env flag (SYSTEM_SASS=1) for libsass to use it. This worked for me:
```
apt-get install libsass1 libsass-dev
env SYSTEM_SASS=1 pip wheel --no-cache-dir --no-deps --wheel-dir=/wheels libsass
```
`libsass-dev` is probably not needed, but I haven't tested it yet.

**Comment by aek** [comment]
I have made a wheel for 0.22.0 since it was taking too long to install it from source and I need it for use it in a Docker Alpine image with arch64 so it must be compatible with musl tags and target platform

You could use it from:
https://pypi.org/project/libsass-wheel/

pip install libsass-wheel

this one works for me:
https://files.pythonhosted.org/packages/f6/51/b8c5e44aecb8789d2ac5d57dc6fd0b788ee3dd93d131a29a723ed581dea9/libsass_wheel-0.22.0-cp312-abi3-musllinux_1_2_aarch64.whl

**Comment by aek** [comment]
I also have go and build several more versions that are dependencies with other softwares that I deploy on different versions. If you need any other particular wheel around this just ping me
